spring:
  application:
    name: currency-conversion-service

#currency-exchange-service:
#  ribbon:
#    listOfServers: http://localhost:8000,http://localhost:8001
server:
  port: 8100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka